### ISSUE TITLE
Bounds Issue

### ISSUE THREAD

**Issue by tastrax** [osmlab/maproulette3#1317] opened 2020-07-16 03:30 UTC
Zooming in to Tasmania I get resulting projects from Romania

https://maproulette.org/browse/challenges?challengeSearch=147.45763778686526%2C-42.886278703448454%2C147.57496833801272%2C-42.83966061151599&location=intersectingMapBounds

I have advised project owner but also wondered if its a bigger issue with MapRoulette?

**Comment by tastrax** [comment] 2020-07-17 23:16
Is this the same issue as https://github.com/osmlab/maproulette3/issues/1297 ?

**Comment by nrotstan** [comment] 2020-07-18 00:22
Hi @tastrax , thanks for the report! Yes, it's likely being caused by #1297, but we'll leave this open until that has been confirmed.

**Comment by tastrax** [comment] 2020-07-20 22:52
I am no longer getting the Romanian roads but I get a false result anyway. Any idea when this issue will be resolved?

https://maproulette.org/browse/challenges?challengeSearch=142.75085449218753%2C-43.67184498322161%2C150.26000976562503%2C-40.655638740061164&location=intersectingMapBounds

**Comment by nrotstan** [comment] 2020-07-20 23:33
The fix for #1297 will be included in the next release, which is currently scheduled for deployment to maproulette.org on Thursday (July 23) at 19:00 UTC.

**Comment by nrotstan** [comment] 2020-07-23 21:38
The fix for #1297 has now been deployed to maproulette.org -- please let me know if you continue to experience problems.

**Closed by nrotstan** 2020-07-23 21:38 UTC
