### ISSUE TITLE
Can't copy from Challenge admin fields

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#522] opened 2018-11-06 19:45 UTC
I am trying to copy text from Challenge wizard fields but can't.

**Comment by nrotstan** [comment] 2018-11-06 19:49
@mvexel This is the form fields when you're editing a challenge?

**Comment by mvexel** [comment] 2018-11-06 19:51
Yes

**Comment by nrotstan** [comment] 2018-11-12 19:30
I'm not able to reproduce this. Is it still happening for you, @mvexel? Is it just the form fields, or does copy/paste not work in general? 

If it's still happening, can you try restarting Chrome and see if that helps? I've run into weird copy/paste problems with Chrome in the past (not in MR, but broadly) that seem to go away with a browser restart.

**Comment by nrotstan** [comment] 2020-01-27 15:05
I'm going to close this issue. Please feel free to reopen it if you continue to experience the problem.

**Closed by nrotstan** 2020-01-27 15:05 UTC
Labels: bug
