### ISSUE TITLE
Last updated date on challenge's manage page only shows today's date 

### ISSUE THREAD

**Issue by aawiseman** [osmlab/maproulette3#1733] opened 2022-05-05 18:50 UTC
Under the manage tab, my challenges only ever show today's date as the Modified date. That's not helpful, I want to know when the tasks were last updated, and I know for a fact that's almost never today. it seems to just include whenever you clicked "Manage" as the "Modified" date. For example I last updated this months ago if not longer ago https://maproulette.org/browse/challenges/17851

On the manage page it says modified today, which is not correct
<img width="582" alt="Screen Shot 2022-05-05 at 11 49 30 AM" src="https://user-images.githubusercontent.com/5025092/167003761-f83ad971-6248-41c9-9e46-e344459a3a12.png">

**Comment by mvexel** [comment] 2022-05-17 15:10
I can confirm this. I think it's a bug. Probably the Challenge gets 'touched' every time you open the admin screen. Assigning to @jschwarz2030 to investigate.

**Comment by mvexel** [comment] 2022-05-17 20:23
@jschwarz2030  and I just discussed this:

The 'Modified' date represents the most recent date on which a Task changed status Users likely expect 'Modified' to mean the most recent date that the tasks were updated *by the Challenge owner*. So we need to change two things:

1. The 'modified' date needs to reflect when the Challenge Owner most recently updated tasks (either by rebuilding the tasks or otherwise adding / modifying / deleting tasks through the front end or API)
2. The wording needs to be changed to make the dates less confusing, see below for suggested new wording:

* "Created" --> "Challenge Created"
* "Modified" --> "Tasks Last Updated"
* "Tasks From" --> "Task Data Sourced"

We can link to https://learn.maproulette.org/media/defining-task-sourced-date/ to explain "task sourced date"

**Comment by jschwarz2030** [comment] 2022-05-17 23:13
new discovery: modification dates are changing every day because of https://github.com/maproulette/maproulette2/pull/910.  @aawiseman is correct.  Even if challenges aren't worked on, they're being updated by the system.

**Closed** 2022-06-15 16:49 UTC
Labels: bug
