### ISSUE TITLE
bug on the Maproulette score board.

### ISSUE THREAD

**Issue by raphaelpe** [osmlab/maproulette3#979] opened 2019-11-10 12:04 UTC
Inglês; 

Good Morning!

I had more than 20,000 thousand points and now I have just over 8,000 points, was the number 1 in Brazil and today I am third, why? I would like the site adm to check and return points earned on Maproulette tasks.

- Português;

Bug no placar de pontos do Maproulette. 

Bom Dia! 

estava com mais de 20.000 mil pontos e agora estou com pouco mais de 8.000 pontos, era o Numero 1° no Brasil e hoje estou em terceiro, porque? gostaria que o adm do site verificasse e devolvesse os pontos adquiridos nas tarefas do Maproulette. 

Raphael de Assis
Recife/PE. 
Brasil

**Comment by nrotstan** [comment] 2019-11-12 16:23
Thanks for the report, @raphaelpe , we will investigate. Has it been 20,000 for a long time and it just suddenly changed to 8,000 or did you only notice the 20,000 for a short time?

**Comment by raphaelpe** [comment] 2019-11-12 18:53
I had over 20,000 points and it's been a long time, I was first in brazil's ranking for quite a while.. and suddenly got that score from now 8,000 points.

**Comment by nrotstan** [comment] 2019-11-12 19:27
Hi @raphaelpe , I've done some investigating and it looks like you've made a total of 1845 status changes to 1815 tasks. At most we [assign 5 points](https://github.com/osmlab/maproulette3/wiki/Point-Scoring) per task (for fixed status), which would be around 9,000 points -- and obviously not all of those tasks were given a fixed status. You can see a breakdown of your user metrics by clicking on your username at the top-right of MapRoulette and choosing "User Metrics". So the 8,000+ seems about right.

I notice that if you look at the Brazil leaderboard for the past month you are number 1 and have just over 3,000 points -- is it possible you were looking at that and seeing 2,000 instead of 20,000?

If it was 20,000, then it seems like that might have been inaccurate and I'm not sure why it would have shown that number. Sorry about that :-(

**Comment by raphaelpe** [comment] 2019-11-12 19:47
Good afternoon nrotstan!

What I see and that I had other tasks that I had created for some time and these tasks seemed absoletous to stay in maproulette in view of that it was a task to fix Street names and many of the Streets already have names, many streets were solved by openstr itself eetMap, so I decided to delete these tasks, I see that these tasks may have influenced my score, because I came to some tasks I have done more than 68% the task, so it seems to me that these tasks are influencing my score, which i have not it was to happen because I did the task and just because I delete since It had no more sense I'm noticing that my score is well below what it really was, because with these deleted tasks you guys from maproulette can't check the exact amount of my points, it seems to me a misguided search of my points, more anyway gets the alert on that score, that's what happened to me! 

I don't know if that was supposed to happen, because it wasn't. since I did the challenge and the points were to be on the scoreboard, regardless of whether I deleted the task or not! 

even so I keep insisting that I did not miss on the scoreboard and that I had even more than 20,000 points, because I've put on a lot of tasks almost all day!  

==============================================================


O Que vejo e que eu tinha outras tarefas que eu tinha criado a algum tempo e essas tarefas parecia absoleta para ficar no maproulette tendo em vista que era tarefa para concertar nomes de Ruas e muitas das Ruas já tem nomes, muitas ruas foram resolvidas pelo proprio OpenStreetMap, então resolvi deletar essas tarefas, eu vejo que essas tarefas pode ter influenciadas na minha pontuação, pois cheguei a algumas tarefas eu ter feito mais de 68% a tarefa, então me parece que essas tarefas estão influenciando na minha pontuação, coisa que não era para acontecer, pois fiz a tarefa e só porque eu exclui já que não tinha mais sentido estou notando que minha pontuação está bem abaixo da que realmente era, pois com essas tarefas deletadas vocês do maproulette não tem como verificar a quantidade exata dos meus pontos, me parece uma pesquisa equivocada dos meus pontos, mais de qualquer forma fica o alerta sobre esse placar, foi o que aconteceu comigo! 

não sei se era pra acontecer isso, pois não era.. já que eu fiz o desafio e os pontos eram para está no placar, independente de ter deletado a tarefa ou não! 

mesmo assim continuo insistindo que eu não errei no placar e que eu tinha mesmo mais de 20.000 pontos, pois concerto muitas tarefas quase que o dia todo!

**Comment by nrotstan** [comment] 2019-11-12 20:32
Ah, okay, that makes more sense. We may need to take a closer look at how we handle challenge deletions. I agree that mappers shouldn't lose points just because an old challenge is deleted.

**Comment by raphaelpe** [comment] 2019-11-13 10:24
That's what happened after I delete the old tasks in maproulette, I ask you to see how not to miss who deletes a task, 

a strong hug.

**Comment by oliver-01** [comment] 2020-02-13 05:49
I had the same issue on challenge 8301 and lost ~10,000 points.

**Comment by nrotstan** [comment] 2020-02-13 20:19
I'm really sorry about this, @oliver-01 :-( We've temporarily halted the process responsible for final deletion of challenges until we get a permanent solution for this in place.

**Comment by nrotstan** [comment] 2020-10-20 21:45
I'm going to close this as we no longer permanently remove challenges from the database, which was the root cause of this problem.

**Closed by nrotstan** 2020-10-20 21:45 UTC
Labels: bug
