### ISSUE TITLE
Why do we get multiple "completion" message from the same project?

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1833] opened 2022-10-05 07:46 UTC
I wonder why I'm getting multiple messages announcing the completion of a challenge I contributed to in the past.

These is how they look like:
![image](https://user-images.githubusercontent.com/5821688/194007622-54716870-a492-49be-9611-39372ac88a52.png)

Isn't it reasonable to assume that contributors will get this message just once, when a challenge is completed?

**Comment by danieldegroot2** [comment] 2022-10-09 20:56
This is a duplicate of #1614.
If this resolves your question, you may close this issue by clicking on the Close issue button under the comment box below.

(cc; @mvexel )

**Comment by mvexel** [comment] 2022-11-23 19:53
Closing in favor of #1614

**Closed by mvexel** 2022-11-23 19:53 UTC
