### ISSUE TITLE
Get rid of new confirmation popup 

### ISSUE THREAD

**Issue by Pepilepioux** [osmlab/maproulette3#732] opened 2019-04-18 20:33 UTC
Hello,
When solving a maproulette task I save a lot of time just by using keyboard shortcuts.
This new confirmation popup is just a pain in the ass because it forces me to drag my mouse from one screen to another each time, it's really bothering.
Could you please at least make that confirmation optionnal ? In user's profile, for example...
I've gone through this hassle just one or two hours to day, and I'm seriously considering giving up...
Thank you !
(Oh, by the way : thanks for maproulette, it's really a great stuff !)

**Comment by nrotstan** [comment] 2019-04-18 20:39
Thanks for the feedback, @Pepilepioux. We overlooked keyboard shortcuts on that dialog, and I can understand your frustration -- my apologies. We'll start by adding support for keyboard shortcuts so you won't have to touch the mouse in most cases, and then we can go from there. We obviously want everyone to have a great experience.

**Comment by map93-osm** [comment] 2019-04-21 01:34
Having keyboard shortcuts would definitely help, but it's still kind of frustrating to have to click two things instead of one to update the task status after each task (and when the task itself isn't that complicated, I end up spending a decent proportion of my time just clicking through the confirmation dialog, which seems kind of silly). I'm guessing the purpose of this is to prevent people from accidentally clicking one of the options, and not realizing what happens when they move onto the next task? In that case, I think it might work better to instead have a banner at the top of the screen that says something like "You've successfully marked this task as fixed. Undo?". That way, it would be easier to figure out what happened, but still continue to the next task without being interrupted quite as much.

Separately from that, it might be a good idea to make the comment box a bit smaller, and change the placeholder text to something like "Your comment (optional)". Initially, I though it was required to submit a comment for every task, which is fairly frustrating until you realize you can just submit it without typing anything.

**Comment by mvexel** [comment] 2019-04-22 20:19
Hey @map93-osm . I understand your position. It's not a decision we made lightly -- changing the workflow in this significant way was done with what we think are good reasons. We wanted to put more emphasis on the way mappers can interact with each other in MapRoulette. Leaving comments on tasks, asking for review, are both important components for that. MapRoulette often gets the critique that it allows 'mindless' armchair mapping by just clicking through tasks and solving them 'on autopilot'. We are really sensitive to this - we want MapRoulette to be a 'good citizen' in the OSM ecosystem. Having the new confirmation dialog forces you (to your annoyance :)) to pause for a moment, making actions performed through MapRoulette more deliberate.

With all that said, and taking into account the philosophy behind this choice as I just explained, we are very open to alternative flows that could accomplish the same goal. 

Your point about the comment box is taken, we will think about how we can make it clearer that a comment is not required.

Thank you for helping think about MapRoulette!

**Comment by map93-osm** [comment] 2019-04-22 23:08
@mvexel I definitely see your point about making mapping more deliberate, and I didn't mean to imply that I disagree with that. There definitely are issues with low-quality fixes to tasks, and I appreciate that you're trying to address that!

I think part of the issue is that, at least in my experience, the maproulette interface isn't really where I'm reflecting about the task. When I'm looking at the task in an editor, I'll spend a decent amount of time trying to understand what the issue is and how best to fix it, but by the time I go back to the maproulette interface to mark the task as completed, I've already come up with a fix I'm satisfied with and saved my changes. Because I'm no longer thinking about the task at that point, the additional step doesn't really add anything that helps improve quality, and ends up just feeling like a roadblock.

Without having more specific examples of the quality issues you've run into, it's a bit difficult for me to propose alternatives, but I wonder if reviewing only a subset of tasks would work; I'm imagining something like this:
* Every time a mapper starts on a new task, the first <i>n</i> tasks they solved get flagged for review, and they recieve feedback on how to improve if necessary.
* If an account is exhibiting unusual behavior (solving tasks very quickly, having an unusually high rate of skipped or fixed tasks, etc.), some of their recent tasks get flagged for review again.
* If they continue to make low-quality edits, their account gets blocked from contributing further to that task.

However, I don't have the data you do about what's currently happening, so maybe this won't address the issue.

**Comment by nrotstan** [comment] 2019-06-21 13:39
We now automatically focus the comment box on the confirmation step, so that a user can immediately begin typing their comment, and have added support for a `[Shift]-Enter` keyboard shortcut to submit confirmation.

**Comment by mvexel** [comment] 2019-08-12 19:53
I think the keyboard shortcut appropriately addresses this. Do you agree @map93-osm @Pepilepioux ? I will leave the issue open to discuss for a little while.

**Comment by mvexel** [comment] 2019-08-15 18:54
Closing now, if this requires more discussion please re-open

**Closed by mvexel** 2019-08-15 18:54 UTC
Labels: UX / UI, discussion, enhancement

**Comment by mvexel** [comment] 2019-10-04 16:00
![](https://github.trello.services/images/mini-trello-icon.png) [Possibility to disable "comment" dialog.](https://trello.com/c/Q2uUhX4p/42-possibility-to-disable-comment-dialog)
